Shopping cart entity and corresponding repository/service layers have been added
BakhmetIvan/spring-boot pull request #10
Opened 2024-05-08 19:12 UTC by BakhmetIvan

2024-05-09 07:15 UTC, Elena-Bruyako requested changes
Let's improve your solution!

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/config/SecurityConfig.java
> +                                        "/swagger-ui/**", "/test/**")
why do you need this?

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/controllers/ShoppingCartController.java
> +                                                   Pageable pageable) {
Why do you need Pageable pageable here?

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/controllers/ShoppingCartController.java
> +                                      @Positive int quantity,
Did you check this endpoint? How do you provide int quantity here?

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/mapper/CartItemMapper.java
> +
```suggestion

```

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/CartItem.java
> +    @ManyToOne(cascade = CascadeType.ALL)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.EAGER)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```
Try to avoid using Eager, read about the problems that could be appeared

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", fetch = FetchType.LAZY)
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

OneToMany has fetchtype lazy by default

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +        cartItem.setShoppingCart(shoppingCartRepository.findShoppingCartByUser(user));
It's better to split the logic, first - find book in DB, second find shopping cart, then cart.getCartItems() and check if book exists there -> increase quantity, if no ->  add book
I mean, it's better to create local variables for find results

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findShoppingCartByUser(user);
```suggestion
        return shoppingCartMapper.toDto(repository.findByUserId(userId));
```

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id).orElseThrow(
```suggestion
        ShoppingCart cart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(itemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
        itemRepository.save(cartItem);
        return cartMapper.toDto(cart);

```

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id).orElseThrow(
```suggestion
        ShoppingCart shoppingCart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(itemId, shoppingCart.getId())
                .orElseThrow(()
```

2024-05-09 07:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/UserServiceImpl.java
> +        shoppingCartService.save(user);
It's better to use cartService.createShoppingCart(user);
where in ShoppingCartServiceImpl
```
@Override
    public void createShoppingCart(User user) {
        ShoppingCart shoppingCart = new ShoppingCart();
        shoppingCart.setUser(user);
        repository.save(shoppingCart);
    }
```

2024-05-10 14:19 UTC, BakhmetIvan commented on src/main/java/mate/academy/library/controllers/ShoppingCartController.java
> +                                                   Pageable pageable) {
The task specified implementing pagination and sorting, and this is the only place where it can be implemented

2024-05-10 14:22 UTC, BakhmetIvan commented on src/main/java/mate/academy/library/controllers/ShoppingCartController.java
> +                                      @Positive int quantity,
I write the quantity in the params. And yeah, it works

2024-05-11 15:49 UTC, BakhmetIvan commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.setCartItems(new LinkedHashSet<>(cartItems.getContent()));
I used LinkedHashSet for correct sorting work

2024-05-13 06:46 UTC, Elena-Bruyako requested changes
Almost perfect!

2024-05-13 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Not fixed

2024-05-13 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", fetch = FetchType.LAZY)
Not fixed

2024-05-13 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +public class ShoppingCartServiceImpl implements ShoppingCartService {
Please add ` @Transactional` where is needed

2024-05-13 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/service/impl/ShoppingCartServiceImpl.java
> +    public CartItemDto saveCartItem(CartItemRequestDto requestDto, User user) {
It's better to return ShoppingCartDto here and in updateQuantity method

2024-05-13 06:46 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/controllers/ShoppingCartController.java
> +@RequestMapping(value = "/cart")
```suggestion
@RequestMapping("/cart")

```

2024-05-14 06:22 UTC, Elena-Bruyako requested changes
Need to fix some comments

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/ShoppingCart.java
> +@RequiredArgsConstructor
```suggestion
```

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/CartItem.java
> +    @JoinColumn(name = "shopping_cart_id")
```suggestion
    @JoinColumn(name = "shopping_cart_id", nullable = false)
```

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/CartItem.java
> +    @JoinColumn(name = "book_id")
```suggestion
    @JoinColumn(name = "book_id", nullable = false)

```

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/model/ShoppingCart.java
> +public class ShoppingCart {
Do we need to add soft delete?

2024-05-14 06:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/library/repository/cartitem/CartItemRepository.java
> +    Page<CartItem> findAllByShoppingCartId(Long id, Pageable pageable);
It looks like you don't use this method

2024-05-15 14:33 UTC, MAMentorFX approved these changes

2024-05-16 11:25 UTC, merged