Hw add tests for books categories
BakhmetIvan/spring-boot pull request #13
Opened 2024-05-28 20:34 UTC by BakhmetIvan

2024-05-28 20:36 UTC, BakhmetIvan commented
![image](https://github.com/BakhmetIvan/spring-boot/assets/123748128/a485995c-1ace-4bc1-8de0-2d6965fac90b)

2024-05-30 09:19 UTC, okuzan requested changes

2024-05-30 09:19 UTC, okuzan commented on src/test/java/mate/academy/library/controller/BookControllerTest.java
> +    }, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
extract setup common to each test to the class level

2024-05-31 15:01 UTC, kerrrusha approved these changes

2024-06-01 11:43 UTC, merged