Hw spring boot criteria query
BakhmetIvan/spring-boot pull request #3
Opened 2024-03-02 19:05 UTC by BakhmetIvan

2024-03-03 18:00 UTC, okuzan requested changes

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/dto/BookSearchParametersDto.java
> +public record BookSearchParametersDto(String[] titles, String[] authors) {
it's a better practice to either make all your DTOs as records, or make all of them as simple classes, mix of both can be confusing

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/model/Book.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id =?")
@SQLRestriction(clause = "is_deleted = FALSE")
```

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/model/Book.java
>      private String coverImage;
```suggestion
    private String coverImage;

```
not consisstent with other fields

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/repository/book/TitleSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("title").in(Arrays.stream(params).toArray());
better extract this literal to a constant

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/repository/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException("Can't find specifications or key " + key));
change p to provider for better readability
change runtime to more specific NoSuchElementException

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/repository/book/BookSpecificationBuilder.java
> +                    .getSpecificationProvider("title")
use .getKey() of provider instead of hardcoding

2024-03-03 18:00 UTC, okuzan commented on src/main/java/mate/academy/library/repository/book/AuthorsSpecificationProvider.java
> +
```suggestion
```

2024-03-05 20:19 UTC, BakhmetIvan commented on src/main/java/mate/academy/library/repository/book/BookSpecificationBuilder.java
> +    private static final String AUTHOR_SPECIFICATION = "author";
It was decided to use constant field values
https://mate.academy/chats/21985?selectedMessageId=1800943&threadId=1800143

2024-03-06 12:42 UTC, okuzan approved these changes

2024-04-21 15:02 UTC, merged